server:
  port: 8888

spring:
  application:
    name: /phonebook-app-frontend

backend:
  phonebook-backend-api: ${BACKEND_API:http://localhost:8081/user/api}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8091}
