kind: Service
apiVersion: v1
metadata:
  name: frontendsvc
  namespace: backend-app-final
spec:
  selector:
    app: phonebook-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer